'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import {
  ArrowLeft, Store, Loader2, CheckCircle2,
} from 'lucide-react';
import { channelsApi, bigcommerceApi } from '@/lib/api';
import ChannelListingActivity from '@/components/channels/ChannelListingActivity';

function shopIdFromStorage() { return localStorage.getItem('shop_id') || '1'; }

interface ChannelConnection {
  id: number;
  channel_type: string;
  channel_api_url?: string | null; // holds the store_hash for BigCommerce, not a full URL
}

// Same per-seller-credential shape as woocommerce-integration/page.tsx —
// a BigCommerce store-level API account is self-serve, generated by the
// seller in their own control panel, no OAuth consent screen to redirect
// through.
export default function BigCommerceIntegrationPage() {
  const [shopId, setShopId] = useState('');
  const [connection, setConnection] = useState<ChannelConnection | null>(null);
  const [loading, setLoading] = useState(true);
  const [confirming, setConfirming] = useState(false);
  const [disconnecting, setDisconnecting] = useState(false);

  const [storeHash, setStoreHash] = useState('');
  const [accessToken, setAccessToken] = useState('');
  const [connecting, setConnecting] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => { setShopId(shopIdFromStorage()); }, []);

  const load = () => {
    if (!shopId) return;
    channelsApi.getConnections(shopId)
      .then((r) => {
        const conns: ChannelConnection[] = r.data ?? [];
        setConnection(conns.find((c) => c.channel_type === 'bigcommerce') ?? null);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, [shopId]);

  const connect = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!storeHash.trim() || !accessToken.trim()) return;
    setConnecting(true); setError('');
    try {
      await bigcommerceApi.connect(shopId, {
        store_hash: storeHash.trim(),
        access_token: accessToken.trim(),
      });
      load();
    } catch (err: any) {
      setError(err?.response?.data?.detail?.message ?? err?.response?.data?.detail ?? 'Connection failed — double-check your store hash and access token.');
    } finally {
      setConnecting(false);
    }
  };

  const disconnect = async () => {
    setDisconnecting(true);
    try {
      await channelsApi.disconnectChannel(shopId, connection!.id);
      setConnection(null);
      setConfirming(false);
    } finally {
      setDisconnecting(false);
    }
  };

  return (
    <div className="p-6 max-w-2xl mx-auto space-y-6">
      <Link href="/dashboard/channels" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition">
        <ArrowLeft className="w-4 h-4" /> Back to Channels
      </Link>

      <div>
        <h1 className="text-xl font-semibold text-foreground">BigCommerce Integration</h1>
        <p className="text-sm text-muted-foreground mt-1">Sync your BigCommerce store — products, orders, and inventory sync to ExiusCart.</p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground gap-2">
          <Loader2 className="w-5 h-5 animate-spin" />
          <span className="text-sm">Loading...</span>
        </div>
      ) : connection ? (
        <div className="space-y-5">
        <div className="bg-card border border-border rounded-xl overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-border">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-lg bg-[#00C9A7]/10 flex items-center justify-center">
                <Store className="w-4 h-4 text-[#00C9A7]" />
              </div>
              <div>
                <p className="font-semibold text-foreground text-sm">BigCommerce</p>
                <p className="text-xs text-muted-foreground truncate max-w-[280px] font-mono">Store: {connection.channel_api_url}</p>
              </div>
            </div>
            <span className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full bg-green-500/10 text-green-600 dark:text-green-400">
              <CheckCircle2 className="w-3 h-3" /> Connected
            </span>
          </div>
          <div className="p-5 space-y-4">
            <p className="text-xs text-muted-foreground bg-muted/50 rounded-lg px-3 py-2.5">
              Products you list from ExiusCart go live on your store immediately — BigCommerce has no marketplace review step, unlike Daraz or Noon.
            </p>
            <div className="pt-3 mt-1 border-t border-border">
              {confirming ? (
                <div className="flex items-center gap-2 flex-wrap">
                  <p className="text-xs text-muted-foreground">Disconnect BigCommerce? Your store stays live, but it stops syncing here.</p>
                  <button onClick={disconnect} disabled={disconnecting}
                    className="text-xs font-medium px-3 py-1.5 rounded-lg bg-destructive text-destructive-foreground hover:bg-destructive/90 transition disabled:opacity-60">
                    {disconnecting ? 'Disconnecting…' : 'Yes, disconnect'}
                  </button>
                  <button onClick={() => setConfirming(false)} disabled={disconnecting}
                    className="text-xs px-3 py-1.5 rounded-lg border border-border hover:bg-muted transition">
                    Cancel
                  </button>
                </div>
              ) : (
                <button onClick={() => setConfirming(true)} className="text-xs text-muted-foreground hover:text-destructive transition">
                  Disconnect BigCommerce
                </button>
              )}
            </div>
          </div>
        </div>
        <ChannelListingActivity shopId={shopId} channelType="bigcommerce" />
        </div>
      ) : (
        <div className="bg-card border border-border rounded-xl">
          <div className="p-5 border-b border-border">
            <p className="font-semibold text-foreground">Connect BigCommerce</p>
            <p className="text-xs text-muted-foreground mt-0.5">Paste your own store's API credentials</p>
          </div>
          <form onSubmit={connect} className="p-5 space-y-4">
            {error && (
              <div className="bg-destructive/10 border border-destructive/30 text-destructive text-sm rounded-lg px-4 py-3">
                {error}
              </div>
            )}
            <div className="bg-muted/50 rounded-lg px-4 py-3 text-xs text-muted-foreground space-y-1.5">
              <p><strong className="text-foreground">Don't have these yet?</strong></p>
              <p>1. In your BigCommerce admin, go to Settings → Store-level API accounts</p>
              <p>2. Click "Create API Account" — grant Products and Orders read/write scopes</p>
              <p>3. Copy the Access Token shown (only shown once) and your store hash (in your admin URL, e.g. store-<strong>abc123</strong>.mybigcommerce.com)</p>
            </div>
            <div>
              <label className="text-sm text-muted-foreground mb-1.5 block">Store Hash *</label>
              <input type="text" value={storeHash} onChange={(e) => setStoreHash(e.target.value)} required
                placeholder="abc123"
                className="w-full px-3 py-2.5 bg-muted border border-border rounded-lg focus:ring-2 focus:ring-primary outline-none text-foreground text-sm font-mono" />
            </div>
            <div>
              <label className="text-sm text-muted-foreground mb-1.5 block">Access Token *</label>
              <input type="password" value={accessToken} onChange={(e) => setAccessToken(e.target.value)} required
                placeholder="••••••••••••••••"
                className="w-full px-3 py-2.5 bg-muted border border-border rounded-lg focus:ring-2 focus:ring-primary outline-none text-foreground text-sm font-mono" />
            </div>
            <button type="submit" disabled={connecting}
              className="w-full py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 transition disabled:opacity-60 flex items-center justify-center gap-2">
              {connecting && <Loader2 className="w-4 h-4 animate-spin" />}
              {connecting ? 'Verifying...' : 'Connect BigCommerce'}
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
