'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import {
  ArrowLeft, CreditCard, Loader2, CheckCircle2,
} from 'lucide-react';
import { channelsApi, whopApi } from '@/lib/api';
import ChannelListingActivity from '@/components/channel-listings/ChannelListingActivity';

function shopIdFromStorage() { return localStorage.getItem('shop_id') || '1'; }

interface ChannelConnection {
  id: number;
  channel_type: string;
  channel_seller_id?: string | null; // holds the Whop company_id
}

// Same self-serve-credential shape as BigCommerce/WooCommerce — a Whop
// Company API key is generated by the seller in their own Whop dashboard,
// no OAuth consent screen to redirect through. Whop is Merchant of Record:
// no business registration needed on the seller's side to get paid — see
// the Channels page's own "Sell Digital Products" section copy.
export default function WhopIntegrationPage() {
  const [shopId, setShopId] = useState('');
  const [connection, setConnection] = useState<ChannelConnection | null>(null);
  const [loading, setLoading] = useState(true);
  const [confirming, setConfirming] = useState(false);
  const [disconnecting, setDisconnecting] = useState(false);

  const [apiKey, setApiKey] = useState('');
  const [companyId, setCompanyId] = useState('');
  const [webhookSecret, setWebhookSecret] = useState('');
  const [connecting, setConnecting] = useState(false);
  const [error, setError] = useState('');
  const [webhookUrl, setWebhookUrl] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => { setShopId(shopIdFromStorage()); }, []);

  const load = () => {
    if (!shopId) return;
    channelsApi.getConnections(shopId)
      .then((r) => {
        const conns: ChannelConnection[] = r.data ?? [];
        setConnection(conns.find((c) => c.channel_type === 'whop') ?? null);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, [shopId]);

  const connect = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!apiKey.trim() || !companyId.trim()) return;
    setConnecting(true); setError('');
    try {
      const res = await whopApi.connect(shopId, {
        api_key: apiKey.trim(),
        company_id: companyId.trim(),
        webhook_signing_secret: webhookSecret.trim() || undefined,
      });
      setWebhookUrl(res.data?.webhook_url ?? '');
      load();
    } catch (err: any) {
      setError(err?.response?.data?.detail?.message ?? err?.response?.data?.detail ?? 'Connection failed — double-check your API key and Company ID.');
    } finally {
      setConnecting(false);
    }
  };

  const disconnect = async () => {
    setDisconnecting(true);
    try {
      await channelsApi.disconnectChannel(shopId, connection!.id);
      setConnection(null);
      setConfirming(false);
    } finally {
      setDisconnecting(false);
    }
  };

  const copyWebhookUrl = () => {
    const full = `${process.env.NEXT_PUBLIC_API_URL || 'https://api.exiuscart.com'}/api/v1${webhookUrl}`;
    navigator.clipboard.writeText(full);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-6 max-w-2xl mx-auto space-y-6">
      <Link href="/dashboard/channels" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition">
        <ArrowLeft className="w-4 h-4" /> Back to Channels
      </Link>

      <div>
        <h1 className="text-xl font-semibold text-foreground">Whop Integration</h1>
        <p className="text-sm text-muted-foreground mt-1">Sell digital products with no business registration needed — Whop is Merchant of Record.</p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground gap-2">
          <Loader2 className="w-5 h-5 animate-spin" />
          <span className="text-sm">Loading...</span>
        </div>
      ) : connection ? (
        <div className="space-y-5">
        <div className="bg-card border border-border rounded-xl overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-border">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-lg bg-[#FA4616]/10 flex items-center justify-center">
                <CreditCard className="w-4 h-4 text-[#FA4616]" />
              </div>
              <div>
                <p className="font-semibold text-foreground text-sm">Whop</p>
                <p className="text-xs text-muted-foreground truncate max-w-[280px] font-mono">Company: {connection.channel_seller_id}</p>
              </div>
            </div>
            <span className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full bg-green-500/10 text-green-600 dark:text-green-400">
              <CheckCircle2 className="w-3 h-3" /> Connected
            </span>
          </div>
          <div className="p-5 space-y-4">
            {webhookUrl && (
              <div className="bg-muted/50 rounded-lg px-4 py-3 text-xs space-y-2">
                <p className="text-foreground font-medium">Last step — register this webhook URL in your Whop dashboard (Developer → Webhooks), event: <code className="font-mono">payment.succeeded</code></p>
                <div className="flex items-center gap-2">
                  <code className="flex-1 bg-background border border-border rounded px-2 py-1.5 font-mono text-[11px] truncate">
                    {(process.env.NEXT_PUBLIC_API_URL || 'https://api.exiuscart.com') + '/api/v1' + webhookUrl}
                  </code>
                  <button onClick={copyWebhookUrl} className="shrink-0 text-xs font-medium px-2.5 py-1.5 rounded-lg border border-border hover:bg-muted transition">
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                </div>
              </div>
            )}
            <p className="text-xs text-muted-foreground bg-muted/50 rounded-lg px-3 py-2.5">
              Whop handles payment and tax compliance for you — you only need a payout destination in your Whop account, no business registration required.
            </p>
            <div className="pt-3 mt-1 border-t border-border">
              {confirming ? (
                <div className="flex items-center gap-2 flex-wrap">
                  <p className="text-xs text-muted-foreground">Disconnect Whop? Your listings stay live on Whop, but stop syncing here.</p>
                  <button onClick={disconnect} disabled={disconnecting}
                    className="text-xs font-medium px-3 py-1.5 rounded-lg bg-destructive text-destructive-foreground hover:bg-destructive/90 transition disabled:opacity-60">
                    {disconnecting ? 'Disconnecting…' : 'Yes, disconnect'}
                  </button>
                  <button onClick={() => setConfirming(false)} disabled={disconnecting}
                    className="text-xs px-3 py-1.5 rounded-lg border border-border hover:bg-muted transition">
                    Cancel
                  </button>
                </div>
              ) : (
                <button onClick={() => setConfirming(true)} className="text-xs text-muted-foreground hover:text-destructive transition">
                  Disconnect Whop
                </button>
              )}
            </div>
          </div>
        </div>
        <ChannelListingActivity shopId={shopId} channelType="whop" />
        </div>
      ) : (
        <div className="bg-card border border-border rounded-xl">
          <div className="p-5 border-b border-border">
            <p className="font-semibold text-foreground">Connect Whop</p>
            <p className="text-xs text-muted-foreground mt-0.5">Paste your own Whop Company API credentials</p>
          </div>
          <form onSubmit={connect} className="p-5 space-y-4">
            {error && (
              <div className="bg-destructive/10 border border-destructive/30 text-destructive text-sm rounded-lg px-4 py-3">
                {error}
              </div>
            )}
            <div className="bg-muted/50 rounded-lg px-4 py-3 text-xs text-muted-foreground space-y-1.5">
              <p><strong className="text-foreground">Don't have these yet?</strong></p>
              <p>1. In your Whop dashboard, go to Developer → API Keys and create a Company API key</p>
              <p>2. Copy your Company ID (shown in your dashboard URL / Company settings)</p>
              <p>3. Optional now, needed before orders can sync: register a webhook (Developer → Webhooks) for <code className="font-mono">payment.succeeded</code> — we'll show you the exact URL to use once connected</p>
            </div>
            <div>
              <label className="text-sm text-muted-foreground mb-1.5 block">Company ID *</label>
              <input type="text" value={companyId} onChange={(e) => setCompanyId(e.target.value)} required
                placeholder="biz_xxxxxxxx"
                className="w-full px-3 py-2.5 bg-muted border border-border rounded-lg focus:ring-2 focus:ring-primary outline-none text-foreground text-sm font-mono" />
            </div>
            <div>
              <label className="text-sm text-muted-foreground mb-1.5 block">API Key *</label>
              <input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} required
                placeholder="••••••••••••••••"
                className="w-full px-3 py-2.5 bg-muted border border-border rounded-lg focus:ring-2 focus:ring-primary outline-none text-foreground text-sm font-mono" />
            </div>
            <div>
              <label className="text-sm text-muted-foreground mb-1.5 block">Webhook Signing Secret (optional)</label>
              <input type="password" value={webhookSecret} onChange={(e) => setWebhookSecret(e.target.value)}
                placeholder="whsec_•••••••••••• — paste after registering the webhook"
                className="w-full px-3 py-2.5 bg-muted border border-border rounded-lg focus:ring-2 focus:ring-primary outline-none text-foreground text-sm font-mono" />
              <p className="text-xs text-muted-foreground mt-1.5">Can be added later — without it, incoming orders won't be signature-verified.</p>
            </div>
            <button type="submit" disabled={connecting}
              className="w-full py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 transition disabled:opacity-60 flex items-center justify-center gap-2">
              {connecting && <Loader2 className="w-4 h-4 animate-spin" />}
              {connecting ? 'Verifying...' : 'Connect Whop'}
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
