"""bundle components allow multiple variant options

Revision ID: b8909792fba9
Revises: 34d9f3dc74de
Create Date: 2026-07-18 19:55:58.435165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8909792fba9'
down_revision: Union[str, None] = '34d9f3dc74de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle_components', sa.Column('allowed_variant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('bundle_components', 'variant_color')
    op.drop_column('bundle_components', 'variant_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle_components', sa.Column('variant_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('bundle_components', sa.Column('variant_color', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('bundle_components', 'allowed_variant_ids')
    # ### end Alembic commands ###
