from fastapi import APIRouter
from app.api.v1.endpoints import auth, users, shops, products, orders, customers, product_fields, admin, shopping, webhooks, hr, marketing, recruitment, attendance, fleet, services, shopify_integration, ai_seo, public, partner, channels, reservations, affiliates, quotations, usage, bundles, expenses, wholesale, advanced_reports, dropshipping, reviews, popups, lemonsqueezy_webhook, daraz

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["Authentication"])
api_router.include_router(users.router, prefix="/users", tags=["Users"])
api_router.include_router(shops.router, prefix="/shops", tags=["Shops"])
api_router.include_router(products.router, prefix="", tags=["Products"])
api_router.include_router(orders.router, prefix="", tags=["Orders"])
api_router.include_router(customers.router, prefix="", tags=["Customers"])
api_router.include_router(product_fields.router, prefix="", tags=["Product Fields & Images"])
api_router.include_router(admin.router, prefix="", tags=["Admin"])
api_router.include_router(shopping.router, prefix="", tags=["Shopping Storefront"])
api_router.include_router(webhooks.router, prefix="", tags=["Webhooks"])
api_router.include_router(hr.router, prefix="", tags=["HR & Payroll"])
api_router.include_router(marketing.router, prefix="", tags=["Marketing"])
api_router.include_router(recruitment.router, prefix="", tags=["Recruitment"])
api_router.include_router(attendance.router, prefix="", tags=["Attendance"])
api_router.include_router(fleet.router, prefix="", tags=["Fleet"])
api_router.include_router(services.router, prefix="", tags=["Services"])
api_router.include_router(shopify_integration.router, prefix="", tags=["Shopify Integration"])
api_router.include_router(ai_seo.router, prefix="", tags=["AI SEO"])
api_router.include_router(public.router, prefix="", tags=["Public"])
api_router.include_router(partner.router, prefix="", tags=["Partner Integrations"])
api_router.include_router(channels.router, prefix="", tags=["Channel Integrations"])
api_router.include_router(reservations.router, prefix="", tags=["Reservations"])
api_router.include_router(affiliates.router, prefix="", tags=["Affiliates"])
api_router.include_router(quotations.router, prefix="", tags=["Quotations"])
api_router.include_router(usage.router, prefix="", tags=["Usage"])
api_router.include_router(bundles.router, prefix="", tags=["Bundles"])
api_router.include_router(expenses.router, prefix="", tags=["Expenses"])
api_router.include_router(wholesale.router, prefix="", tags=["Wholesale"])
api_router.include_router(advanced_reports.router, prefix="", tags=["Advanced Reports"])
api_router.include_router(dropshipping.router, prefix="", tags=["Dropshipping"])
api_router.include_router(reviews.router, prefix="", tags=["Reviews"])
api_router.include_router(popups.router, prefix="", tags=["Storefront Popups"])
api_router.include_router(lemonsqueezy_webhook.router, prefix="", tags=["Lemon Squeezy Webhook"])
api_router.include_router(daraz.router, prefix="", tags=["Daraz Integration"])
