from fastapi import APIRouter
from app.api.v1.endpoints import auth, users, shops, products, orders, customers, product_fields, admin, shopping, webhooks, hr, marketing, recruitment, attendance, fleet, services, shopify_integration, ai_seo, public, partner, channels, reservations, affiliates, quotations, usage, bundles, expenses, wholesale, advanced_reports, dropshipping, reviews, popups, lemonsqueezy_webhook, daraz, noon, ebay, tiktok, woocommerce, etsy, signup_forms, checkout, wallet, custom_product_fields, blog, digital_delivery, bigcommerce, ad_intelligence, testimonials, whop, gumroad, video_gen, storefront_insights, prodora_digital, social_posting, whatsapp_marketing

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["Authentication"])
api_router.include_router(users.router, prefix="/users", tags=["Users"])
api_router.include_router(shops.router, prefix="/shops", tags=["Shops"])
api_router.include_router(products.router, prefix="", tags=["Products"])
api_router.include_router(orders.router, prefix="", tags=["Orders"])
api_router.include_router(customers.router, prefix="", tags=["Customers"])
api_router.include_router(product_fields.router, prefix="", tags=["Product Fields & Images"])
api_router.include_router(admin.router, prefix="", tags=["Admin"])
api_router.include_router(shopping.router, prefix="", tags=["Shopping Storefront"])
api_router.include_router(webhooks.router, prefix="", tags=["Webhooks"])
api_router.include_router(hr.router, prefix="", tags=["HR & Payroll"])
api_router.include_router(marketing.router, prefix="", tags=["Marketing"])
api_router.include_router(recruitment.router, prefix="", tags=["Recruitment"])
api_router.include_router(attendance.router, prefix="", tags=["Attendance"])
api_router.include_router(fleet.router, prefix="", tags=["Fleet"])
api_router.include_router(services.router, prefix="", tags=["Services"])
api_router.include_router(shopify_integration.router, prefix="", tags=["Shopify Integration"])
api_router.include_router(ai_seo.router, prefix="", tags=["AI SEO"])
api_router.include_router(public.router, prefix="", tags=["Public"])
api_router.include_router(partner.router, prefix="", tags=["Partner Integrations"])
api_router.include_router(channels.router, prefix="", tags=["Channel Integrations"])
api_router.include_router(reservations.router, prefix="", tags=["Reservations"])
api_router.include_router(affiliates.router, prefix="", tags=["Affiliates"])
api_router.include_router(quotations.router, prefix="", tags=["Quotations"])
api_router.include_router(usage.router, prefix="", tags=["Usage"])
api_router.include_router(bundles.router, prefix="", tags=["Bundles"])
api_router.include_router(expenses.router, prefix="", tags=["Expenses"])
api_router.include_router(wholesale.router, prefix="", tags=["Wholesale"])
api_router.include_router(advanced_reports.router, prefix="", tags=["Advanced Reports"])
api_router.include_router(dropshipping.router, prefix="", tags=["Dropshipping"])
api_router.include_router(reviews.router, prefix="", tags=["Reviews"])
api_router.include_router(popups.router, prefix="", tags=["Storefront Popups"])
api_router.include_router(signup_forms.router, prefix="", tags=["Signup Forms"])
api_router.include_router(checkout.router, prefix="", tags=["Storefront Checkout"])
api_router.include_router(wallet.router, prefix="", tags=["Wallet"])
api_router.include_router(custom_product_fields.router, prefix="", tags=["Custom Product Fields"])
api_router.include_router(blog.router, prefix="", tags=["Blog"])
api_router.include_router(digital_delivery.router, prefix="", tags=["Digital Delivery"])
api_router.include_router(lemonsqueezy_webhook.router, prefix="", tags=["Lemon Squeezy Webhook"])
api_router.include_router(daraz.router, prefix="", tags=["Daraz Integration"])
api_router.include_router(noon.router, prefix="", tags=["Noon Integration"])
api_router.include_router(ebay.router, prefix="", tags=["eBay Integration"])
api_router.include_router(tiktok.router, prefix="", tags=["TikTok Shop Integration"])
api_router.include_router(woocommerce.router, prefix="", tags=["WooCommerce Integration"])
api_router.include_router(etsy.router, prefix="", tags=["Etsy Integration"])
api_router.include_router(bigcommerce.router, prefix="", tags=["BigCommerce Integration"])
api_router.include_router(whop.router, prefix="", tags=["Whop Integration"])
api_router.include_router(gumroad.router, prefix="", tags=["Gumroad Integration"])
api_router.include_router(video_gen.router, prefix="", tags=["AI Video Generation"])
api_router.include_router(storefront_insights.router, prefix="", tags=["Storefront Insights"])
api_router.include_router(prodora_digital.router, prefix="", tags=["Prodora Digital Bundles"])
api_router.include_router(social_posting.router, prefix="", tags=["Social Posting"])
api_router.include_router(whatsapp_marketing.router, prefix="", tags=["WhatsApp Marketing"])
api_router.include_router(ad_intelligence.router, prefix="", tags=["Ad Intelligence"])
api_router.include_router(testimonials.router, prefix="", tags=["Testimonials"])
